FROM node:14

# set working directory
WORKDIR /app

# Install development tools
RUN npm install typescript -g

# copy project file
COPY package.json .

# install ALL node_modules, including 'devDependencies'
RUN npm install

# copy entire project
COPY . .

# compile source in typescript
RUN tsc